### ISSUE TITLE
Hide card additional information shows list moved date

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board-apps#104]
Steps to reproduce in Restyaboard 0.6.5 using Chrome, Edge, or FF:

1. Install hide card additional information plugin
2. Admin -> Apps, enable plugin
3. Set all `Hide ***` settings to `true`
4. Go to any board, none of the cards show card id, creation date, created user, or list moved date
![image](https://user-images.githubusercontent.com/33263752/40630699-b25d5efc-6289-11e8-99b0-6eb092ba2a5f.png)
5. Re-order a card by moving it above or below another card or by moving it to a different list, list moved date shows on the card that was just moved.
![image](https://user-images.githubusercontent.com/33263752/40630707-be6947ce-6289-11e8-8458-55d029db8bea.png)

**Comment by sridhar391** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/8398a086609320467e48afb834a21ba48dc395cd and closing the issue
