### ISSUE TITLE
¿HowTo install apps on RestyaBoard?

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board-apps#35]
Hi!

¿Can you explain how to integrate Apps on my own RestyaBoard?

I want to try and maybe develop some but I don't find the "apps" dir to put them.

Regards

**Comment by ssivachidambaram** [comment]
You have to create a directory inside client folder named "apps" and then download the apps and extract it inside apps folder.

**Comment by dfragac** [comment]
Thx!
