### ISSUE TITLE
Auto Archive Expired Cards app Integration

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board-apps#51]

**Comment by ssivachidambaram** [comment]
Done.

**Comment by dfragac** [comment]
¿Is this app still available or there's a function to auto archive cards by some "custom" rules? (ex: It there is in "done" list and it is "older than a month" then > archive it.

**Comment by ssivachidambaram** [comment]
Currently its in `dev` branch and it will be available in upcoming release. Admin can set lists name as `Todo`, `Doing` & `Done` in settings. Auto archive will apply based on the `Done` list.
