### ISSUE TITLE
togetherjs is not enabling

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board-apps#54]
I installed togetherjs app for restyaboard but it's not possible to enable it. The app appears in "Apps" view but when I try to enable it, it stays "disabled".

**Comment by ssivachidambaram** [comment]
Can you please check after provide write permission to `client/apps/r_togetherjs/app.json` and let us know your feedback?

**Comment by dfragac** [comment]
I'm using restya on docker for testing purposes. This is permissions on r_togetherjs folder

`
root@9058c8bfef95:/usr/share/nginx/html/client/apps# ls -lahR r_togetherjs
r_togetherjs:
total 24K
drwxr-xr-x 4 root root 4.0K Apr 26 08:32 .
drwxr-xr-x 5 root root 4.0K Apr 26 08:37 ..
-rw-r--r-- 1 root root   73 Apr 26 08:32 README.md
-rw-r--r-- 1 root root  468 Apr 26 08:32 app.json
drwxr-xr-x 2 root root 4.0K Apr 26 08:32 img
drwxr-xr-x 2 root root 4.0K Apr 26 08:32 js

r_togetherjs/img:
total 12K
drwxr-xr-x 2 root root 4.0K Apr 26 08:32 .
drwxr-xr-x 4 root root 4.0K Apr 26 08:32 ..
-rw-r--r-- 1 root root 2.6K Apr 26 08:32 togetherjs.png

r_togetherjs/js:
total 12K
drwxr-xr-x 2 root root 4.0K Apr 26 08:32 .
drwxr-xr-x 4 root root 4.0K Apr 26 08:32 ..
-rw-r--r-- 1 root root 3.9K Apr 26 08:32 app.js
`

**Comment by ssivachidambaram** [comment]
`-rw-r--r-- 1 root root  468 Apr 26 08:32 app.json`

Can you please provide write/full permission (0777, 0755) for above file?

**Comment by dfragac** [comment]
I tried 0777 and it works fine. i'll try 755 and report feedback.

**Comment by ssivachidambaram** [comment]
Ok.
