### ISSUE TITLE
App related issues

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board-apps#68]
- Seo checklist, website qa checklist not working 
- Uncaught TypeError: Cannot read property 'r_auto_archive_expired_cards' of null
- In apps if click Zapier Connect its not working.
- In apps if click Post my comments to Slack its not working.
- In SEO checklist pop up if click import template button its not working
- Unable to disable the apps in admin control panel
-  After select estimated time, submit button is not working properly.
- Unable to import the QA Checklists Board. It displayed an error message as "Website QA Checklists board create failed"
- Support ticket - disable

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/commit/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
